// automatically generated by the FlatBuffers compiler, do not modify

package mongo_serialization

const (
	ValueTypeLong   = 0
	ValueTypeDouble = 1
	ValueTypeString = 2
)

var EnumNamesValueType = map[int]string{
	ValueTypeLong:   "Long",
	ValueTypeDouble: "Double",
	ValueTypeString: "String",
}
