// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package mongo_serialization

type ValueType = int8
const (
	ValueTypeInt ValueType = 0
	ValueTypeLong ValueType = 1
	ValueTypeFloat ValueType = 2
	ValueTypeDouble ValueType = 3
	ValueTypeString ValueType = 4
)

var EnumNamesValueType = map[ValueType]string{
	ValueTypeInt:"Int",
	ValueTypeLong:"Long",
	ValueTypeFloat:"Float",
	ValueTypeDouble:"Double",
	ValueTypeString:"String",
}

